/// This file contains the list of industries that are available for selection in the app.
///
/// The list is used in the sign-up process to allow users to select the industry they belong to.
///
/// {@category Constants}
const industries = {
  'fashion': 'Fashion',
  'beauty_and_cosmetics': 'Beauty and Cosmetics',
  'skincare': 'Skincare',
  'makeup': 'Makeup',
  'haircare': 'Haircare',
  'mens_fashion': 'Men\'s Fashion',
  'luxury_fashion': 'Luxury Fashion',
  'streetwear': 'Streetwear',
  'modeling': 'Modeling',
  'fitness': 'Fitness',
  'yoga_and_meditation': 'Yoga and Meditation',
  'mental_health': 'Mental Health',
  'nutrition_and_diet': 'Nutrition and Diet',
  'weight_loss': 'Weight Loss',
  'alternative_medicine': 'Alternative Medicine',
  'physiotherapy': 'Physiotherapy',
  'personal_training': 'Personal Training',
  'cooking_and_recipes': 'Cooking and Recipes',
  'baking': 'Baking',
  'food_reviews': 'Food Reviews',
  'restaurants_and_cafes': 'Restaurants and Cafes',
  'vegan_and_plant_based': 'Vegan and Plant-Based',
  'food_styling': 'Food Styling',
  'wine_and_alcohol': 'Wine and Alcohol',
  'coffee_culture': 'Coffee Culture',
  'solo_travel': 'Solo Travel',
  'luxury_travel': 'Luxury Travel',
  'adventure_travel': 'Adventure Travel',
  'van_life': 'Van Life',
  'backpacking': 'Backpacking',
  'city_guides': 'City Guides',
  'glamping': 'Glamping',
  'consumer_electronics': 'Consumer Electronics',
  'mobile_phones_and_accessories': 'Mobile Phones and Accessories',
  'software_and_apps': 'Software and Apps',
  'ai_and_robotics': 'AI and Robotics',
  'gaming': 'Gaming',
  'programming_and_coding': 'Programming and Coding',
  'startups': 'Startups',
  'entrepreneurship': 'Entrepreneurship',
  'investing': 'Investing',
  'real_estate': 'Real Estate',
  'crypto_and_blockchain': 'Crypto and Blockchain',
  'freelancing_and_side_hustles': 'Freelancing and Side Hustles',
  'financial_planning': 'Financial Planning',
  'marketing_and_sales': 'Marketing and Sales',
  'photography': 'Photography',
  'graphic_design': 'Graphic Design',
  'illustration': 'Illustration',
  'art_and_painting': 'Art and Painting',
  'architecture': 'Architecture',
  'interior_design': 'Interior Design',
  'street_art': 'Street Art',
  'calligraphy': 'Calligraphy',
  'celebrities': 'Celebrities',
  'movies_and_tv_shows': 'Movies and TV Shows',
  'music_and_bands': 'Music and Bands',
  'comedy_and_memes': 'Comedy and Memes',
  'dance': 'Dance',
  'theater_and_performing_arts': 'Theater and Performing Arts',
  'anime_and_manga': 'Anime and Manga',
  'online_courses': 'Online Courses',
  'self_help': 'Self-Help',
  'language_learning': 'Language Learning',
  'career_coaching': 'Career Coaching',
  'book_reviews': 'Book Reviews',
  'study_tips': 'Study Tips',
  'parenting': 'Parenting',
  'dogs_and_cats': 'Dogs and Cats',
  'exotic_animals': 'Exotic Animals',
  'wildlife_photography': 'Wildlife Photography',
  'pet_care': 'Pet Care',
  'animal_rescue_and_adoption': 'Animal Rescue and Adoption',
  'aquarium_and_fish': 'Aquarium and Fish',
  'parenting_life': 'Parenting',
  'marriage_and_relationships': 'Marriage and Relationships',
  'home_decor': 'Home Decor',
  'gardening': 'Gardening',
  'minimalism': 'Minimalism',
  'daily_life_and_vlogging': 'Daily Life and Vlogging',
  'product_reviews': 'Product Reviews',
  'hiking_and_camping': 'Hiking and Camping',
  'fishing': 'Fishing',
  'hunting': 'Hunting',
  'running_and_marathons': 'Running and Marathons',
  'cycling': 'Cycling',
  'water_sports': 'Water Sports',
  'extreme_sports': 'Extreme Sports',
  'cars_and_motorcycles': 'Cars and Motorcycles',
  'car_reviews': 'Car Reviews',
  'car_restoration': 'Car Restoration',
  'off_road_vehicles': 'Off-Road Vehicles',
  'electric_vehicles': 'Electric Vehicles',
  'car_culture': 'Car Culture',
  'console_gaming': 'Console Gaming',
  'pc_gaming': 'PC Gaming',
  'mobile_gaming': 'Mobile Gaming',
  'game_reviews': 'Game Reviews',
  'streaming_and_youtube_gaming': 'Streaming and YouTube Gaming',
  'game_development': 'Game Development',
  'eco_friendly_products': 'Eco-Friendly Products',
  'zero_waste_living': 'Zero Waste Living',
  'recycling_and_upcycling': 'Recycling and Upcycling',
  'climate_change_awareness': 'Climate Change Awareness',
  'conservation_efforts': 'Conservation Efforts',
  'human_rights': 'Human Rights',
  'social_justice': 'Social Justice',
  'environmental_activism': 'Environmental Activism',
  'feminism': 'Feminism',
  'political_commentary': 'Political Commentary',
  'handmade_crafts': 'Handmade Crafts',
  'woodworking': 'Woodworking',
  'sewing_and_knitting': 'Sewing and Knitting',
  'upcycling': 'Upcycling',
  'candle_making': 'Candle Making',
  'diy_home_renovation': 'DIY Home Renovation',
  'real_estate_investment': 'Real Estate Investment',
  'tiny_homes': 'Tiny Homes',
  'landscaping': 'Landscaping',
  'yachting_and_sailing': 'Yachting and Sailing',
  'private_jets': 'Private Jets',
  'luxury_real_estate': 'Luxury Real Estate',
  'high_end_fashion': 'High-End Fashion',
  'fine_dining_and_gourmet': 'Fine Dining and Gourmet',
  'astrology': 'Astrology',
  'tarot_reading': 'Tarot Reading',
  'reiki_and_energy_healing': 'Reiki and Energy Healing',
  'meditation_and_mindfulness': 'Meditation and Mindfulness',
  'crystal_healing': 'Crystal Healing'
};
